apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template: 
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-go
          image: raphaeldiasc/goapp

